site_name: Sublime Suricate
repo_url: https://github.com/nsubiron/SublimeSuricate

pages:
- 'Home': 'index.md'
- 'Quick Guide': 'quick-guide.md'
- 'API Reference': 'api-reference.md'

markdown_extensions:
- admonition:
